package dev.erancha.folderscanner.consumer.duplicates;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import dev.erancha.folderscanner.consumer.shell.ShellScript;
import dev.erancha.folderscanner.consumer.shell.SoftDeletePathEncoder;
import dev.erancha.folderscanner.data.Format;

/**
 * Writes the duplicate-removal shell script.
 *
 * The first path of each group is emitted as a commented-out "# KEPT" line so the user can
 * pick a different keeper before running. The active commands operate on the rest.
 *
 * The shebang, staleness guard, trash-bin setup, confirm banner, per-file delete line, and shell
 * quoting are delegated to {@link ShellScript}; this class owns only the duplicates-specific header
 * (phase timings) and the per-group framing.
 */
public final class ScriptWriter {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private ScriptWriter() {}

    public static void write(Path scriptPath, Path sourceTree, DuplicateReport report,
            boolean hardDelete) throws IOException {
        Files.createDirectories(scriptPath.toAbsolutePath().getParent());

        List<Path> redundantPaths = report.groups().stream()
                .flatMap(g -> g.paths().subList(1, g.paths().size()).stream())
                .toList();
        Map<Path, String> encodedNames = SoftDeletePathEncoder.encodeAll(redundantPaths);

        try (PrintWriter w = new PrintWriter(
                Files.newBufferedWriter(scriptPath, StandardCharsets.UTF_8))) {
            ShellScript.writeShebang(w);
            ShellScript.writeStalenessGuard(w, java.time.Instant.now().getEpochSecond());
            writeHeader(w, sourceTree, report, hardDelete);
            if (!hardDelete) ShellScript.writeBinDeclaration(w);
            ShellScript.writeConfirmBanner(w, report.redundantFileCount(), report.redundantBytes(),
                    hardDelete);
            if (!hardDelete) ShellScript.writeBinMkdir(w);

            for (DuplicateReport.Group g : report.groups()) {
                List<Path> paths = g.paths();
                w.printf("# ---- size=%s  count=%d  waste=%s ----%n",
                        Format.humanBytes(g.fileSizeBytes()),
                        paths.size(),
                        Format.humanBytes((paths.size() - 1L) * g.fileSizeBytes()));

                w.printf("# %s \"%s\"   # KEPT (first by sort order)%n",
                        hardDelete ? "rm" : "mv", ShellScript.shellQuote(paths.get(0)));

                for (int i = 1; i < paths.size(); i++) {
                    Path p = paths.get(i);
                    ShellScript.emitDeletion(w, p, encodedNames.get(p), hardDelete);
                }
                w.println();
            }
        }
    }

    private static void writeHeader(PrintWriter w, Path sourceTree, DuplicateReport r,
            boolean hardDelete) {
        w.println("# ##########################################################################");
        w.println("# ##  GENERATED BY folder-scanner --consumer=duplicates                   ##");
        w.printf ("# ##  Generated at: %s                                                    %n",
                STAMP.format(LocalDateTime.now()));
        w.printf ("# ##  Source tree:  %s%n", sourceTree.toAbsolutePath());
        w.printf ("# ##  Phase 1 (size buckets): %d ms   Phase 2 (hashing): %d ms%n",
                r.phase1ElapsedMs(), r.phase2ElapsedMs());
        w.printf ("# ##  Mode: %s%n", hardDelete ? "HARD DELETE (rm)" : "SOFT DELETE (mv to bin)");
        w.println("# ##                                                                      ##");
        w.println("# ##  !!! WARNING: REVIEW EVERY LINE BEFORE RUNNING !!!                   ##");
        w.println("# ##########################################################################");
        w.println();
    }
}
