package dev.erancha.folderscanner.consumer.filemanager;

import dev.erancha.folderscanner.consumer.shell.ShellScript;
import dev.erancha.folderscanner.consumer.shell.SoftDeletePathEncoder;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Writes the filemanager deletion script: a flat list of files to quarantine or remove.
 *
 * Unlike the duplicates script there are no groups and no keeper — every matched file is a
 * deletion target. The shebang, staleness guard, trash-bin setup, confirm banner, per-file line,
 * and shell quoting are delegated to {@link ShellScript}; this class owns only the filemanager
 * header frame.
 */
public final class DeleteScript {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private DeleteScript() {}

    public static void write(Path scriptPath, Path sourceTree, List<Path> paths, long totalBytes,
            boolean hardDelete) throws IOException {
        Files.createDirectories(scriptPath.toAbsolutePath().getParent());
        Map<Path, String> encodedNames = SoftDeletePathEncoder.encodeAll(paths);

        try (PrintWriter w = new PrintWriter(
                Files.newBufferedWriter(scriptPath, StandardCharsets.UTF_8))) {
            ShellScript.writeShebang(w);
            ShellScript.writeStalenessGuard(w, java.time.Instant.now().getEpochSecond());
            writeHeader(w, sourceTree, paths.size(), totalBytes, hardDelete);
            if (!hardDelete) ShellScript.writeBinDeclaration(w);
            ShellScript.writeConfirmBanner(w, paths.size(), totalBytes, hardDelete);
            if (!hardDelete) ShellScript.writeBinMkdir(w);

            for (Path p : paths) {
                ShellScript.emitDeletion(w, p, encodedNames.get(p), hardDelete);
            }
            w.println();
        }
    }

    private static void writeHeader(PrintWriter w, Path sourceTree, int fileCount, long totalBytes,
            boolean hardDelete) {
        w.println("# ##########################################################################");
        w.println("# ##  GENERATED BY folder-scanner --consumer=filemanager --action=delete  ##");
        w.printf ("# ##  Generated at: %s                                                    %n",
                STAMP.format(LocalDateTime.now()));
        w.printf ("# ##  Source tree:  %s%n", sourceTree.toAbsolutePath());
        w.printf ("# ##  Files: %d  Bytes: %s%n", fileCount,
                dev.erancha.folderscanner.data.Format.humanBytes(totalBytes));
        w.printf ("# ##  Mode: %s%n", hardDelete ? "HARD DELETE (rm)" : "SOFT DELETE (mv to bin)");
        w.println("# ##                                                                      ##");
        w.println("# ##  !!! WARNING: REVIEW EVERY LINE BEFORE RUNNING !!!                   ##");
        w.println("# ##########################################################################");
        w.println();
    }
}
