package com.example.folderscanner.consumer.duplicates;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.example.folderscanner.data.Format;

/**
 * Writes the duplicate-removal shell script.
 *
 * The first path of each group is emitted as a commented-out "# KEPT" line so the user can
 * pick a different keeper before running. The active commands operate on the rest.
 *
 * Soft delete = mv to a bin under the script's own directory; hard delete = rm in place.
 * Filenames in the scanned tree are untrusted input — every interpolation site goes through
 * shellQuote to prevent shell injection.
 */
public final class ScriptWriter {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private ScriptWriter() {}

    public static void write(Path scriptPath, Path sourceTree, DuplicateReport report,
            boolean hardDelete) throws IOException {
        Files.createDirectories(scriptPath.toAbsolutePath().getParent());

        List<Path> redundantPaths = report.groups().stream()
                .flatMap(g -> g.paths().subList(1, g.paths().size()).stream())
                .toList();
        Map<Path, String> encodedNames = SoftDeletePathEncoder.encodeAll(redundantPaths);

        try (PrintWriter w = new PrintWriter(
                Files.newBufferedWriter(scriptPath, StandardCharsets.UTF_8))) {
            writeHeader(w, sourceTree, report, hardDelete);
            writeBannerAndConfirm(w, report, hardDelete);
            if (!hardDelete) w.println("mkdir -p \"$BIN\"\n");

            for (DuplicateReport.Group g : report.groups()) {
                List<Path> paths = g.paths();
                w.printf("# ---- size=%s  count=%d  waste=%s ----%n",
                        Format.humanBytes(g.fileSizeBytes()),
                        paths.size(),
                        Format.humanBytes((paths.size() - 1L) * g.fileSizeBytes()));

                w.printf("# %s \"%s\"   # KEPT (first by sort order)%n",
                        hardDelete ? "rm" : "mv", shellQuote(paths.get(0)));

                for (int i = 1; i < paths.size(); i++) {
                    Path p = paths.get(i);
                    if (hardDelete) {
                        w.printf("rm \"%s\"%n", shellQuote(p));
                    } else {
                        // Both source path and bin name are attacker-controlled (filenames in
                        // the scanned tree). Each interpolation site goes through shellQuote.
                        w.printf("mv \"%s\" \"$BIN/%s\"%n",
                                shellQuote(p), shellQuoteString(encodedNames.get(p)));
                    }
                }
                w.println();
            }
        }
    }

    private static void writeHeader(PrintWriter w, Path sourceTree, DuplicateReport r,
            boolean hardDelete) {
        w.println("#!/usr/bin/env bash");
        w.println("set -euo pipefail");
        w.println();
        w.println("# ##########################################################################");
        w.println("# ##  GENERATED BY folder-scanner --consumer=duplicates                   ##");
        w.printf ("# ##  Generated at: %s                                                    %n",
                STAMP.format(LocalDateTime.now()));
        w.printf ("# ##  Source tree:  %s%n", sourceTree.toAbsolutePath());
        w.printf ("# ##  Phase 1 (size buckets): %d ms   Phase 2 (hashing): %d ms%n",
                r.phase1ElapsedMs(), r.phase2ElapsedMs());
        w.printf ("# ##  Mode: %s%n", hardDelete ? "HARD DELETE (rm)" : "SOFT DELETE (mv to bin)");
        w.println("# ##                                                                      ##");
        w.println("# ##  !!! WARNING: REVIEW EVERY LINE BEFORE RUNNING !!!                   ##");
        w.println("# ##########################################################################");
        w.println();
        if (!hardDelete) {
            // BIN is resolved relative to the script's own location so the script works from
            // any cwd (and so the bin doesn't end up wherever the user happened to be).
            w.println("BIN=\"$(cd \"$(dirname \"$0\")\" && pwd)/trash\"");
            w.println();
        }
    }

    private static void writeBannerAndConfirm(
            PrintWriter w, DuplicateReport r, boolean hardDelete) {
        String verb = hardDelete ? "DELETE" : "MOVE";
        String prompt = hardDelete ? "DELETE in capitals" : "y";
        String expected = hardDelete ? "DELETE" : "y";
        w.println("cat <<'BANNER'");
        w.println();
        w.println("  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        w.printf ("  !!  YOU ARE ABOUT TO %s %d FILES (%s)%n",
                verb, r.redundantFileCount(), Format.humanBytes(r.redundantBytes()));
        if (hardDelete) {
            w.println("  !!  This action is IRREVERSIBLE (hard rm).               !!");
        } else {
            w.println("  !!  Files can be recovered by moving them back manually. !!");
        }
        w.println("  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        w.println();
        w.println("BANNER");
        w.printf("read -r -p \"Type %s to proceed: \" CONFIRM%n", prompt);
        w.printf("[ \"$CONFIRM\" = \"%s\" ] || { echo \"Aborted.\"; exit 1; }%n", expected);
        w.println();
    }

    /**
     * Escapes the four characters that retain special meaning inside double-quoted shell
     * arguments (\, ", $, `). Order matters: backslash must be replaced first, otherwise the
     * substitutions added by the later steps would themselves get re-escaped.
     *
     * Limitation: literal newlines and other control characters are passed through unchanged.
     * On Unix, a filename can legitimately contain {@code \n}, and the resulting {@code mv}
     * or {@code rm} line would be split across two shell commands. Out of scope for the
     * target environments (the duplicate finder is run against user data trees, not adversarial
     * fuzzing inputs); call out here so a future caller does not assume otherwise.
     */
    static String shellQuote(Path p) {
        return shellQuoteString(p.toString());
    }

    static String shellQuoteString(String s) {
        return s
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("`", "\\`");
    }
}
