package com.example.folderscanner.consumer;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import com.example.folderscanner.data.Format;

/**
 * Writes the duplicate-removal shell script.
 *
 * Soft delete (default): mv each redundant file to BIN/encoded-name.
 * Hard delete: rm each redundant file.
 *
 * The first path in every group (lexicographically smallest, sort done
 * in phase 2) is commented out with a # KEPT marker; the user can edit
 * the script before running to choose a different keeper.
 */
public final class ScriptWriter {

    /** Timestamp format used in the generated script header. */
    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private ScriptWriter() {}

    /** Write the script for the given report to scriptPath. */
    public static void write(Path scriptPath, Path sourceTree, DuplicateReport report,
            boolean hardDelete) throws IOException {
        Files.createDirectories(scriptPath.toAbsolutePath().getParent());

        // Pre-compute bin names for every redundant path so the script has no
        // ambiguity at run time. Skip per-group index 0 (the keeper).
        List<Path> redundantPaths = report.groups().stream()
                .flatMap(g -> g.paths().subList(1, g.paths().size()).stream())
                .toList();
        Map<Path, String> binNames = BinName.encodeAll(redundantPaths);

        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(scriptPath, StandardCharsets.UTF_8))) {
            writeHeader(w, sourceTree, report, hardDelete);
            writeBannerAndConfirm(w, report, hardDelete);
            if (!hardDelete) w.println("mkdir -p \"$BIN\"\n");

            for (DuplicateReport.Group g : report.groups()) {
                List<Path> paths = g.paths();
                w.printf("# ---- size=%s  count=%d  waste=%s ----%n",
                        Format.humanBytes(g.fileSizeBytes()),
                        paths.size(),
                        Format.humanBytes((paths.size() - 1L) * g.fileSizeBytes()));

                // Keeper line — first path, commented.
                w.printf("# %s \"%s\"   # KEPT (first by sort order)%n",
                        hardDelete ? "rm" : "mv", shellQuote(paths.get(0)));

                // Redundants — active commands.
                for (int i = 1; i < paths.size(); i++) {
                    Path p = paths.get(i);
                    if (hardDelete) {
                        w.printf("rm \"%s\"%n", shellQuote(p));
                    } else {
                        // Filenames in the scanned tree are untrusted input. A file named
                        // foo"; rm -rf $HOME; #  reaches this line with both interpolations
                        // controlled by the attacker — escaping only the path side would
                        // still let the bin half break out of the surrounding double quotes.
                        w.printf("mv \"%s\" \"$BIN/%s\"%n",
                                shellQuote(p), shellQuoteString(binNames.get(p)));
                    }
                }
                w.println();
            }
        }
    }

    /** Write the shebang, set -euo pipefail, and the comment block header. */
    private static void writeHeader(PrintWriter w, Path sourceTree, DuplicateReport r,
            boolean hardDelete) {
        w.println("#!/usr/bin/env bash");
        w.println("set -euo pipefail");
        w.println();
        w.println("# ##########################################################################");
        w.println("# ##  GENERATED BY folder-scanner --consumer=duplicates                   ##");
        w.printf ("# ##  Generated at: %s                                                    %n",
                STAMP.format(LocalDateTime.now()));
        w.printf ("# ##  Source tree:  %s%n", sourceTree.toAbsolutePath());
        w.printf ("# ##  Phase 1 (size buckets): %d ms   Phase 2 (hashing): %d ms%n",
                r.phase1ElapsedMs(), r.phase2ElapsedMs());
        w.printf ("# ##  Mode: %s%n", hardDelete ? "HARD DELETE (rm)" : "SOFT DELETE (mv to bin)");
        w.println("# ##                                                                      ##");
        w.println("# ##  !!! WARNING: REVIEW EVERY LINE BEFORE RUNNING !!!                   ##");
        w.println("# ##########################################################################");
        w.println();
        if (!hardDelete) {
            w.println("BIN=\"./trash\"");
            w.println();
        }
    }

    /** Write the interactive warning banner and read-confirm guard. */
    private static void writeBannerAndConfirm(PrintWriter w, DuplicateReport r, boolean hardDelete) {
        String verb = hardDelete ? "DELETE" : "MOVE";
        String prompt = hardDelete ? "DELETE in capitals" : "y";
        String expected = hardDelete ? "DELETE" : "y";
        w.println("cat <<'BANNER'");
        w.println();
        w.println("  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        w.printf ("  !!  YOU ARE ABOUT TO %s %d FILES (%s)%n",
                verb, r.redundantFileCount(), Format.humanBytes(r.redundantBytes()));
        if (hardDelete) {
            w.println("  !!  This action is IRREVERSIBLE (hard rm).               !!");
        } else {
            w.println("  !!  Files can be recovered by moving them back manually. !!");
        }
        w.println("  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        w.println();
        w.println("BANNER");
        w.printf("read -r -p \"Type %s to proceed: \" CONFIRM%n", prompt);
        w.printf("[ \"$CONFIRM\" = \"%s\" ] || { echo \"Aborted.\"; exit 1; }%n", expected);
        w.println();
    }

    /**
     * Quoting for paths embedded inside double-quoted shell arguments.
     * Escapes backslash, double quote, dollar sign, and backtick - the
     * four characters that retain special meaning inside double quotes.
     * Single quotes need no handling. Order matters: backslash must come
     * first so the substitutions we add are not themselves re-escaped.
     * Package-private so the unit test in the same package can call it directly.
     */
    static String shellQuote(Path p) {
        return shellQuoteString(p.toString());
    }

    /**
     * String-input variant of shellQuote used for substitutions that are not
     * filesystem paths (currently the bin filename in the mv target). Same
     * four-character escape set and the same order-sensitive backslash-first
     * rule. Every value interpolated into a double-quoted shell argument must
     * go through this — the source path and the bin name are both injection
     * sites in mv "<src>" "$BIN/<bin>".
     */
    static String shellQuoteString(String s) {
        return s
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("`", "\\`");
    }
}
